package com.honestefforts.fixengine.model.universal;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;

/**
 * Based on ISO-3166: <a href="https://www.iso.org/iso-3166-country-codes.html">link</a>
 */
@Getter
@FieldDefaults(makeFinal=true, level= AccessLevel. PRIVATE)
@AllArgsConstructor
public enum CountryCode {
  AF("AFG", 4, "Afghanistan", "Afghanistan (l')"),
  AL("ALB", 8, "Albania", "Albanie (l')"),
  DZ("DZA", 12, "Algeria", "Algérie (l')"),
  AS("ASM", 16, "American Samoa", "Samoa américaines (les)"),
  AD("AND", 20, "Andorra", "Andorre (l')"),
  AO("AGO", 24, "Angola", "Angola (l')"),
  AI("AIA", 660, "Anguilla", "Anguilla"),
  AQ("ATA", 10, "Antarctica", "Antarctique (l')"),
  AG("ATG", 28, "Antigua and Barbuda", "Antigua-et-Barbuda"),
  AR("ARG", 32, "Argentina", "Argentine (l')"),
  AM("ARM", 51, "Armenia", "Arménie (l')"),
  AW("ABW", 533, "Aruba", "Aruba"),
  AU("AUS", 36, "Australia", "Australie (l')"),
  AT("AUT", 40, "Austria", "Autriche (l')"),
  AZ("AZE", 31, "Azerbaijan", "Azerbaïdjan (l')"),
  BS("BHS", 44, "Bahamas (the)", "Bahamas (les)"),
  BH("BHR", 48, "Bahrain", "Bahreïn"),
  BD("BGD", 50, "Bangladesh", "Bangladesh (le)"),
  BB("BRB", 52, "Barbados", "Barbade (la)"),
  BY("BLR", 112, "Belarus", "Bélarus (le)"),
  BE("BEL", 56, "Belgium", "Belgique (la)"),
  BZ("BLZ", 84, "Belize", "Belize (le)"),
  BJ("BEN", 204, "Benin", "Bénin (le)"),
  BM("BMU", 60, "Bermuda", "Bermudes (les)"),
  BT("BTN", 64, "Bhutan", "Bhoutan (le)"),
  BO("BOL", 68, "Bolivia (Plurinational State of)", "Bolivie (État plurinational de)"),
  BQ("BES", 535, "Bonaire, Sint Eustatius and Saba", "Bonaire, Saint-Eustache et Saba"),
  BA("BIH", 70, "Bosnia and Herzegovina", "Bosnie-Herzégovine (la)"),
  BW("BWA", 72, "Botswana", "Botswana (le)"),
  BV("BVT", 74, "Bouvet Island", "Bouvet (l'Île)"),
  BR("BRA", 76, "Brazil", "Brésil (le)"),
  IO("IOT", 86, "British Indian Ocean Territory (the)", "Indien (le Territoire britannique de l'océan)"),
  BN("BRN", 96, "Brunei Darussalam", "Brunéi Darussalam (le)"),
  BG("BGR", 100, "Bulgaria", "Bulgarie (la)"),
  BF("BFA", 854, "Burkina Faso", "Burkina Faso (le)"),
  BI("BDI", 108, "Burundi", "Burundi (le)"),
  CV("CPV", 132, "Cabo Verde", "Cabo Verde"),
  KH("KHM", 116, "Cambodia", "Cambodge (le)"),
  CM("CMR", 120, "Cameroon", "Cameroun (le)"),
  CA("CAN", 124, "Canada", "Canada (le)"),
  KY("CYM", 136, "Cayman Islands (the)", "Caïmans (les Îles)"),
  CF("CAF", 140, "Central African Republic (the)", "République centrafricaine (la)"),
  TD("TCD", 148, "Chad", "Tchad (le)"),
  CL("CHL", 152, "Chile", "Chili (le)"),
  CN("CHN", 156, "China", "Chine (la)"),
  CX("CXR", 162, "Christmas Island", "Christmas (l'Île)"),
  CC("CCK", 166, "Cocos (Keeling) Islands (the)", "Cocos (les Îles)/ Keeling (les Îles)"),
  CO("COL", 170, "Colombia", "Colombie (la)"),
  KM("COM", 174, "Comoros (the)", "Comores (les)"),
  CD("COD", 180, "Congo (the Democratic Republic of the)", "Congo (la République démocratique du)"),
  CG("COG", 178, "Congo (the)", "Congo (le)"),
  CK("COK", 184, "Cook Islands (the)", "Cook (les Îles)"),
  CR("CRI", 188, "Costa Rica", "Costa Rica (le)"),
  HR("HRV", 191, "Croatia", "Croatie (la)"),
  CU("CUB", 192, "Cuba", "Cuba"),
  CW("CUW", 531, "Curaçao", "Curaçao"),
  CY("CYP", 196, "Cyprus", "Chypre"),
  CZ("CZE", 203, "Czechia", "Tchéquie (la)"),
  CI("CIV", 384, "Côte d'Ivoire", "Côte d'Ivoire (la)"),
  DK("DNK", 208, "Denmark", "Danemark (le)"),
  DJ("DJI", 262, "Djibouti", "Djibouti"),
  DM("DMA", 212, "Dominica", "Dominique (la)"),
  DO("DOM", 214, "Dominican Republic (the)", "dominicaine (la République)"),
  EC("ECU", 218, "Ecuador", "Équateur (l')"),
  EG("EGY", 818, "Egypt", "Égypte (l')"),
  SV("SLV", 222, "El Salvador", "El Salvador"),
  GQ("GNQ", 226, "Equatorial Guinea", "Guinée équatoriale (la)"),
  ER("ERI", 232, "Eritrea", "Érythrée (l')"),
  EE("EST", 233, "Estonia", "Estonie (l')"),
  SZ("SWZ", 748, "Eswatini", "Eswatini (l')"),
  ET("ETH", 231, "Ethiopia", "Éthiopie (l')"),
  FK("FLK", 238, "Falkland Islands (the) [Malvinas]", "Falkland (les Îles)/Malouines (les Îles)"),
  FO("FRO", 234, "Faroe Islands (the)", "Féroé (les Îles)"),
  FJ("FJI", 242, "Fiji", "Fidji (les)"),
  FI("FIN", 246, "Finland", "Finlande (la)"),
  FR("FRA", 250, "France", "France (la)"),
  GF("GUF", 254, "French Guiana", "Guyane française (la )"),
  PF("PYF", 258, "French Polynesia", "Polynésie française (la)"),
  TF("ATF", 260, "French Southern Territories (the)", "Terres australes françaises (les)"),
  GA("GAB", 266, "Gabon", "Gabon (le)"),
  GM("GMB", 270, "Gambia (the)", "Gambie (la)"),
  GE("GEO", 268, "Georgia", "Géorgie (la)"),
  DE("DEU", 276, "Germany", "Allemagne (l')"),
  GH("GHA", 288, "Ghana", "Ghana (le)"),
  GI("GIB", 292, "Gibraltar", "Gibraltar"),
  GR("GRC", 300, "Greece", "Grèce (la)"),
  GL("GRL", 304, "Greenland", "Groenland (le)"),
  GD("GRD", 308, "Grenada", "Grenade (la)"),
  GP("GLP", 312, "Guadeloupe", "Guadeloupe (la)"),
  GU("GUM", 316, "Guam", "Guam"),
  GT("GTM", 320, "Guatemala", "Guatemala (le)"),
  GG("GGY", 831, "Guernsey", "Guernesey"),
  GN("GIN", 324, "Guinea", "Guinée (la)"),
  GW("GNB", 624, "Guinea-Bissau", "Guinée-Bissau (la)"),
  GY("GUY", 328, "Guyana", "Guyana (le)"),
  HT("HTI", 332, "Haiti", "Haïti"),
  HM("HMD", 334, "Heard Island and McDonald Islands", "Heard-et-Îles MacDonald (l'Île)"),
  VA("VAT", 336, "Holy See (the)", "Saint-Siège (le)"),
  HN("HND", 340, "Honduras", "Honduras (le)"),
  HK("HKG", 344, "Hong Kong", "Hong Kong"),
  HU("HUN", 348, "Hungary", "Hongrie (la)"),
  IS("ISL", 352, "Iceland", "Islande (l')"),
  IN("IND", 356, "India", "Inde (l')"),
  ID("IDN", 360, "Indonesia", "Indonésie (l')"),
  IR("IRN", 364, "Iran (Islamic Republic of)", "Iran (République Islamique d')"),
  IQ("IRQ", 368, "Iraq", "Iraq (l')"),
  IE("IRL", 372, "Ireland", "Irlande (l')"),
  IM("IMN", 833, "Isle of Man", "Île de Man"),
  IL("ISR", 376, "Israel", "Israël"),
  IT("ITA", 380, "Italy", "Italie (l')"),
  JM("JAM", 388, "Jamaica", "Jamaïque (la)"),
  JP("JPN", 392, "Japan", "Japon (le)"),
  JE("JEY", 832, "Jersey", "Jersey"),
  JO("JOR", 400, "Jordan", "Jordanie (la)"),
  KZ("KAZ", 398, "Kazakhstan", "Kazakhstan (le)"),
  KE("KEN", 404, "Kenya", "Kenya (le)"),
  KI("KIR", 296, "Kiribati", "Kiribati"),
  KP("PRK", 408, "Korea (the Democratic People's Republic of)", "Corée (la République populaire démocratique de)"),
  KR("KOR", 410, "Korea (the Republic of)", "Corée (la République de)"),
  KW("KWT", 414, "Kuwait", "Koweït (le)"),
  KG("KGZ", 417, "Kyrgyzstan", "Kirghizistan (le)"),
  LA("LAO", 418, "Lao People's Democratic Republic (the)", "Lao (la République démocratique populaire)"),
  LV("LVA", 428, "Latvia", "Lettonie (la)"),
  LB("LBN", 422, "Lebanon", "Liban (le)"),
  LS("LSO", 426, "Lesotho", "Lesotho (le)"),
  LR("LBR", 430, "Liberia", "Libéria (le)"),
  LY("LBY", 434, "Libya", "Libye (la)"),
  LI("LIE", 438, "Liechtenstein", "Liechtenstein (le)"),
  LT("LTU", 440, "Lithuania", "Lituanie (la)"),
  LU("LUX", 442, "Luxembourg", "Luxembourg (le)"),
  MO("MAC", 446, "Macao", "Macao"),
  MG("MDG", 450, "Madagascar", "Madagascar"),
  MW("MWI", 454, "Malawi", "Malawi (le)"),
  MY("MYS", 458, "Malaysia", "Malaisie (la)"),
  MV("MDV", 462, "Maldives", "Maldives (les)"),
  ML("MLI", 466, "Mali", "Mali (le)"),
  MT("MLT", 470, "Malta", "Malte"),
  MH("MHL", 584, "Marshall Islands (the)", "Marshall (les Îles)"),
  MQ("MTQ", 474, "Martinique", "Martinique (la)"),
  MR("MRT", 478, "Mauritania", "Mauritanie (la)"),
  MU("MUS", 480, "Mauritius", "Maurice"),
  YT("MYT", 175, "Mayotte", "Mayotte"),
  MX("MEX", 484, "Mexico", "Mexique (le)"),
  FM("FSM", 583, "Micronesia (Federated States of)", "Micronésie (États fédérés de)"),
  MD("MDA", 498, "Moldova (the Republic of)", "Moldova (la République de)"),
  MC("MCO", 492, "Monaco", "Monaco"),
  MN("MNG", 496, "Mongolia", "Mongolie (la)"),
  ME("MNE", 499, "Montenegro", "Monténégro (le)"),
  MS("MSR", 500, "Montserrat", "Montserrat"),
  MA("MAR", 504, "Morocco", "Maroc (le)"),
  MZ("MOZ", 508, "Mozambique", "Mozambique (le)"),
  MM("MMR", 104, "Myanmar", "Myanmar (le)"),
  NA("NAM", 516, "Namibia", "Namibie (la)"),
  NR("NRU", 520, "Nauru", "Nauru"),
  NP("NPL", 524, "Nepal", "Népal (le)"),
  NL("NLD", 528, "Netherlands (Kingdom of the)", "Pays-Bas (Royaume des)"),
  NC("NCL", 540, "New Caledonia", "Nouvelle-Calédonie (la)"),
  NZ("NZL", 554, "New Zealand", "Nouvelle-Zélande (la)"),
  NI("NIC", 558, "Nicaragua", "Nicaragua (le)"),
  NE("NER", 562, "Niger (the)", "Niger (le)"),
  NG("NGA", 566, "Nigeria", "Nigéria (le)"),
  NU("NIU", 570, "Niue", "Niue"),
  NF("NFK", 574, "Norfolk Island", "Norfolk (l'Île)"),
  MK("MKD", 807, "North Macedonia", "Macédoine du Nord (la)"),
  MP("MNP", 580, "Northern Mariana Islands (the)", "Mariannes du Nord (les Îles)"),
  NO("NOR", 578, "Norway", "Norvège (la)"),
  OM("OMN", 512, "Oman", "Oman"),
  PK("PAK", 586, "Pakistan", "Pakistan (le)"),
  PW("PLW", 585, "Palau", "Palaos (les)"),
  PS("PSE", 275, "Palestine, State of", "Palestine, État de"),
  PA("PAN", 591, "Panama", "Panama (le)"),
  PG("PNG", 598, "Papua New Guinea", "Papouasie-Nouvelle-Guinée (la)"),
  PY("PRY", 600, "Paraguay", "Paraguay (le)"),
  PE("PER", 604, "Peru", "Pérou (le)"),
  PH("PHL", 608, "Philippines (the)", "Philippines (les)"),
  PN("PCN", 612, "Pitcairn", "Pitcairn"),
  PL("POL", 616, "Poland", "Pologne (la)"),
  PT("PRT", 620, "Portugal", "Portugal (le)"),
  PR("PRI", 630, "Puerto Rico", "Porto Rico"),
  QA("QAT", 634, "Qatar", "Qatar (le)"),
  RO("ROU", 642, "Romania", "Roumanie (la)"),
  RU("RUS", 643, "Russian Federation (the)", "Russie (la Fédération de)"),
  RW("RWA", 646, "Rwanda", "Rwanda (le)"),
  RE("REU", 638, "Réunion", "Réunion (La)"),
  BL("BLM", 652, "Saint Barthélemy", "Saint-Barthélemy"),
  SH("SHN", 654, "Saint Helena, Ascension and Tristan da Cunha", "Sainte-Hélène, Ascension et Tristan da Cunha"),
  KN("KNA", 659, "Saint Kitts and Nevis", "Saint-Kitts-et-Nevis"),
  LC("LCA", 662, "Saint Lucia", "Sainte-Lucie"),
  MF("MAF", 663, "Saint Martin (French part)", "Saint-Martin (partie française)"),
  PM("SPM", 666, "Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon"),
  VC("VCT", 670, "Saint Vincent and the Grenadines", "Saint-Vincent-et-les Grenadines"),
  WS("WSM", 882, "Samoa", "Samoa (le)"),
  SM("SMR", 674, "San Marino", "Saint-Marin"),
  ST("STP", 678, "Sao Tome and Principe", "Sao Tomé-et-Principe"),
  SA("SAU", 682, "Saudi Arabia", "Arabie saoudite (l')"),
  SN("SEN", 686, "Senegal", "Sénégal (le)"),
  RS("SRB", 688, "Serbia", "Serbie (la)"),
  SC("SYC", 690, "Seychelles", "Seychelles (les)"),
  SL("SLE", 694, "Sierra Leone", "Sierra Leone (la)"),
  SG("SGP", 702, "Singapore", "Singapour"),
  SX("SXM", 534, "Sint Maarten (Dutch part)", "Saint-Martin (partie néerlandaise)"),
  SK("SVK", 703, "Slovakia", "Slovaquie (la)"),
  SI("SVN", 705, "Slovenia", "Slovénie (la)"),
  SB("SLB", 90, "Solomon Islands", "Salomon (les Îles)"),
  SO("SOM", 706, "Somalia", "Somalie (la)"),
  ZA("ZAF", 710, "South Africa", "Afrique du Sud (l')"),
  GS("SGS", 239, "South Georgia and the South Sandwich Islands", "Géorgie du Sud-et-les Îles Sandwich du Sud (la)"),
  SS("SSD", 728, "South Sudan", "Soudan du Sud (le)"),
  ES("ESP", 724, "Spain", "Espagne (l')"),
  LK("LKA", 144, "Sri Lanka", "Sri Lanka"),
  SD("SDN", 729, "Sudan (the)", "Soudan (le)"),
  SR("SUR", 740, "Suriname", "Suriname (le)"),
  SJ("SJM", 744, "Svalbard and Jan Mayen", "Svalbard et l'Île Jan Mayen (le)"),
  SE("SWE", 752, "Sweden", "Suède (la)"),
  CH("CHE", 756, "Switzerland", "Suisse (la)"),
  SY("SYR", 760, "Syrian Arab Republic (the)", "République arabe syrienne (la)"),
  TW("TWN", 158, "Taiwan (Province of China)", "Taïwan (Province de Chine)"),
  TJ("TJK", 762, "Tajikistan", "Tadjikistan (le)"),
  TZ("TZA", 834, "Tanzania, the United Republic of", "Tanzanie (la République-Unie de)"),
  TH("THA", 764, "Thailand", "Thaïlande (la)"),
  TL("TLS", 626, "Timor-Leste", "Timor-Leste (le)"),
  TG("TGO", 768, "Togo", "Togo (le)"),
  TK("TKL", 772, "Tokelau", "Tokelau (les)"),
  TO("TON", 776, "Tonga", "Tonga (les)"),
  TT("TTO", 780, "Trinidad and Tobago", "Trinité-et-Tobago (la)"),
  TN("TUN", 788, "Tunisia", "Tunisie (la)"),
  TM("TKM", 795, "Turkmenistan", "Turkménistan (le)"),
  TC("TCA", 796, "Turks and Caicos Islands (the)", "Turks-et-Caïcos (les Îles)"),
  TV("TUV", 798, "Tuvalu", "Tuvalu (les)"),
  TR("TUR", 792, "Türkiye", "Türkiye (la)"),
  UG("UGA", 800, "Uganda", "Ouganda (l')"),
  UA("UKR", 804, "Ukraine", "Ukraine (l')"),
  AE("ARE", 784, "United Arab Emirates (the)", "Émirats arabes unis (les)"),
  GB("GBR", 826, "United Kingdom of Great Britain and Northern Ireland (the)", "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)"),
  UM("UMI", 581, "United States Minor Outlying Islands (the)", "Îles mineures éloignées des États-Unis (les)"),
  US("USA", 840, "United States of America (the)", "États-Unis d'Amérique (les)"),
  UY("URY", 858, "Uruguay", "Uruguay (l')"),
  UZ("UZB", 860, "Uzbekistan", "Ouzbékistan (l')"),
  VU("VUT", 548, "Vanuatu", "Vanuatu (le)"),
  VE("VEN", 862, "Venezuela (Bolivarian Republic of)", "Venezuela (République bolivarienne du)"),
  VN("VNM", 704, "Viet Nam", "Viet Nam (le)"),
  VG("VGB", 92, "Virgin Islands (British)", "Vierges britanniques (les Îles)"),
  VI("VIR", 850, "Virgin Islands (U.S.)", "Vierges des États-Unis (les Îles)"),
  WF("WLF", 876, "Wallis and Futuna", "Wallis-et-Futuna"),
  EH("ESH", 732, "Western Sahara*", "Sahara occidental (le)*"),
  YE("YEM", 887, "Yemen", "Yémen (le)"),
  ZM("ZMB", 894, "Zambia", "Zambie (la)"),
  ZW("ZWE", 716, "Zimbabwe", "Zimbabwe (le)"),
  AX("ALA", 248, "Åland Islands", "Åland(les Îles)");

  String threeLetterCode;
  int digitCode;
  String englishName;
  String frenchName;

  private static final Map<String, CountryCode> lookupMap = Arrays.stream(CountryCode.values())
      .collect(Collectors.toMap(Enum::name, Function.identity()));

  public static boolean isAValidCountryCode(String strCountryCode) {
    return lookupMap.containsKey(strCountryCode);
  }
}
